# Part 1 ---- Hypothesis Testing

## Objective
To test whether the weekly operating costs are higher than the theoretical cost model.

Theoretical Cost Model:

W = 1000 + 5X

Where:
- X = Number of units produced
- X = 600 units

In [1]:
# Import required libraries
import math
from scipy.stats import norm

# Given data
sample_mean = 3050
X = 600
sigma = 5 * 25
n = 25
alpha = 0.05

# Calculate theoretical mean
mu = 1000 + (5 * X)

print("Theoretical Mean (μ) =", mu)

Theoretical Mean (μ) = 4000


## Step 1: State Hypotheses

Null Hypothesis (H₀):
The operating cost follows the old model.

H₀ : μ = 4000

Alternative Hypothesis (H₁):
Operating cost is higher than the old model.

H₁ : μ > 4000

In [2]:
# Display hypotheses
print("Null Hypothesis (H0): µ = 4000")
print("Alternative Hypothesis (H1): µ > 4000")

Null Hypothesis (H0): µ = 4000
Alternative Hypothesis (H1): µ > 4000


### Step-by-Step Hypothesis Testing
1. **Null Hypothesis ($H_0$):** $\mu = 4000$ (The theoretical cost model is accurate).
2. **Alternative Hypothesis ($H_1$):** $\mu > 4000$ (The weekly operating costs are higher than the model suggests).
3. **Test Statistic:** We use the Z-test because the population distribution of units is normal and the standard deviation is provided.
4. **Alpha Level:** $\alpha = 0.05$.

## Step 2: Calculate Z-Test Statistic

Formula:

z = (x̄ - μ) / (σ / √n)

In [3]:
# Calculate z-test statistic
z = (sample_mean - mu) / (sigma / math.sqrt(n))

print("Z-Test Statistic =", round(z, 2))

Z-Test Statistic = -38.0


## Step 3: Find Critical Value

For 5% significance level:
Critical Value = 1.645

In [4]:
# Find critical value
critical_value = norm.ppf(1 - alpha)

print("Critical value=", round(critical_value, 3))

Critical value= 1.645


## Step 4: Decision Making

Decision Rule:
- If z > critical value → Reject H₀
- Otherwise → Fail to Reject H₀

In [5]:
# Decision making
if z > critical_value:
    print("Decision: Reject Null Hypothesis")
else:
    print("Decision: Fail to Reject Null Hypothesis")

Decision: Fail to Reject Null Hypothesis


### Final Decision & Business Conclusion
* **Statistical Decision:** Since our calculated Z-value (-38.0) is completely less than the critical value (1.645), we **Fail to Reject the Null Hypothesis**. 
* **Business Insight:** The restaurant owners' claim is statistically invalid. They claimed costs are *higher* than the model, but the sample data shows their average cost (Rs. 3050) is actually significantly *lower* than the model's theoretical cost (Rs. 4000). The current cost model ($W = 1000 + 5X$) does not underestimate the costs.

# Part 2 ---- Confidence Interval

### Rationale for Distribution Selection
* **T-Distribution (Task A):** Used because the sample size is small ($n=15$) and the **population standard deviation is unknown**. We rely on the sample standard deviation here.
* **Z-Distribution (Task B):** Used because the **population standard deviation is known** ($\sigma = 0.2$), allowing for a more precise estimate despite the small sample size.

## Objective
Estimate the mean durability of print-heads
using 99% confidence interval.

In [6]:
# Import required libraries
import numpy as np
from scipy.stats import t

# Given sample data
data = [1.13, 1.55, 1.43, 0.92, 1.25,
        1.36, 1.32, 0.85, 1.07, 1.48,
        1.20, 1.33, 1.18, 1.22, 1.29]

print(data)

[1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.2, 1.33, 1.18, 1.22, 1.29]


## Step 1: Calculate Sample Statistics

In [7]:
# Convert into numpy array
data = np.array(data)

# Basic calculations
n = len(data)
mean = np.mean(data)
sample_sd = np.std(data, ddof=1)

print("Sample Size =", n)
print("Sample Mean =", round(mean, 3))
print("Sample Standard Deviation =", round(sample_sd, 3))

Sample Size = 15
Sample Mean = 1.239
Sample Standard Deviation = 0.193


## Part (a): 99% Confidence Interval using Sample SD

Since:
- sample size is small
- population standard deviation is unknown

We use t-distribution.

In [8]:
# Confidence level
confidence = 0.99
alpha = 1 - confidence

# t critical value
t_value = t.ppf(1 - alpha/2, df=n-1)

print("t Critical Value =", round(t_value, 3))

t Critical Value = 2.977


In [9]:
# Margin of error
margin_error_t = t_value * (sample_sd / math.sqrt(n))

print("Margin of Error =", round(margin_error_t, 3))


Margin of Error = 0.148


In [10]:
# Confidence interval using t-distribution
lower_t = mean - margin_error_t
upper_t = mean + margin_error_t

print("99% Confidence Interval using t-distribution")
print("Lower Limit =", round(lower_t, 3))
print("Upper Limit =", round(upper_t, 3))

99% Confidence Interval using t-distribution
Lower Limit = 1.09
Upper Limit = 1.387


## Part (b): 99% Confidence Interval using Population SD

Population standard deviation is known:

σ = 0.2

Therefore, z-distribution is used.

In [11]:
# Given population standard deviation
population_sd = 0.2

In [12]:
# Z critical value
z_value = norm.ppf(1 - alpha/2)

print("Z Critical value =", round(z_value, 3))

Z Critical value = 2.576


In [13]:
# Margin of error
margin_error_z = z_value * (population_sd / math.sqrt(n))

print("Margin of Error =", round(margin_error_z, 3))

Margin of Error = 0.133


In [14]:
# Confidence interval using z-distribution
lower_z = mean - margin_error_z
upper_z = mean + margin_error_z

print("99% Confidence Interval using z-distribution")
print("Lower limit =", round(lower_z, 3))
print("Upper limit =", round(upper_z, 3))

99% Confidence Interval using z-distribution
Lower limit = 1.106
Upper limit = 1.372
